### ISSUE TITLE
Memoranda of Understanding

### ISSUE THREAD

**Issue by drkrynstrng** [admindatahandbook/book#1]
Currently, there is a Special Topics section for Model Data Use Agreements. I think it would also be useful to have a section covering Memoranda of Understanding and how they differ from DUAs. MoUs seem to be used for formally establishing (long-term) research partnerships between data providers and research groups, which complement more specific data use agreements for specific research projects. However, there is little guidance to be found on why, when, and how to use MoUs with respect to administrative data.

**Comment by larsvilhuber** [comment]
@drkrynstrng Good comment, but the precise content has yet to emerge, and the chapter may yet be called "legal agreements" to encompass both of the above scenarios, including defining what all the possible terms are that show up in practice.

**Comment by larsvilhuber** [comment]
@jimhshen to monitor when we get the chapter on legal agreements as feedback.

**Comment by larsvilhuber** [comment]
This is (somewhat) covered in the DUA chapter.
