### ISSUE TITLE
Layout of PCRI chapter

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#102]
Various fixes and final copy-edits to PCRI chapter.

**Comment by larsvilhuber** [comment]
- change to bib file (Gurung and Lerner, needs URL and check)

**Comment by jimhshen** [comment]
The PCRI pull broke the build, and pulling pdf3 didn't fix it eithe.

https://github.com/admindatahandbook/book/runs/1253785326

**Comment by larsvilhuber** [comment]
Dang. Fixing it.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Should be fixed.

**Comment by larsvilhuber** [comment]
Closing this issue for now
