### ISSUE TITLE
Why did you remove the references section at the end of the book for HTML?

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#106]
Now the references show up randomly under third party licenses again.

https://admindatahandbook.mit.edu/book/v1.0-rc4/third-party-licenses.html

**Comment by larsvilhuber** [comment]
Not intentionally

**Comment by jimhshen** [comment]
I see that the PDFs from today don't have a references section. Is that accomplished by configuring it in the various tex preambles? I can't find a bookdown configuration that lets us suppress it automatically.

Surrounding the [references div tag](https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html) with the invisible block does work. See [testing](https://admindatahandbook.mit.edu/book/testing/third-party-licenses.html). I don't know if that will break the latex version.

**Comment by larsvilhuber** [comment]
I think that's a side effect of the non-functional if_latex_output code, and the chapterbib stuff. It's as intended...

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Did you want to suppress the end of book bibliography? If so I'll update the latest version with the invisible block fix to avoid having the visible error.

**Comment by jimhshen** [comment]
Oh, just checked, that won't work. Putting the invisible div block will suppress references at the end of the chapters as well. I'm going to revert to the previous version which had the visible references section.

**Comment by larsvilhuber** [comment]
Here's a workaround:

Make the references a 3rd level section:
`### References {- #invisible}`

In style.css change
```
.invisible {
  display: none;
}
```
to
```
.invisible, #invisible {
  display: none;
}
```
Done.

**Comment by jimhshen** [comment]
That seems to work, thanks.
