### ISSUE TITLE
Latex In-line references formatted strangely

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#109]
Page 134 of handbook_color_2020-10-14 has some of the German language in-line citations being formatted strangely (extra spaces):

![image](https://user-images.githubusercontent.com/20117905/96192079-49b00600-0f13-11eb-9c74-7c408e418562.png)

For comparison, here is the web version:

![image](https://user-images.githubusercontent.com/20117905/96192177-7a903b00-0f13-11eb-9bb4-91d65d59b7d5.png)

**Comment by larsvilhuber** [comment]
That seems to be a quirk in the bibtex processing. It's somehow getting confused between "Bundesministerium... (BMAS) (2017)" and removing the second part. 

The abbreviation is not necessary in the reference list. 

Here's the fix @jimhshen 
- In Zotero, remove the various abbreviations in the author field, eg. "(BMAS)"
- re-export the bib file

It will get picked up next time it compiles. (note that there is one source with the inverted situation, with abbreviation first, then in parentheses the full name - RWI).

There is a workaround for LaTeX but it wouldn't work for the HTML version. Just remove it.

**Comment by jimhshen** [comment]
Updated with other copy edit changes in latest pull from issue54
