### ISSUE TITLE
Integrate Google Analytics into Handbook

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#12]

**Comment by larsvilhuber** [comment]
Need an API key from JPAL webfolks.

**Comment by jimhshen** [comment]
https://stackoverflow.com/questions/41376989/how-to-include-google-analytics-in-an-rmarkdown-generated-github-page

**Comment by larsvilhuber** [comment]
Yes, that's the right solution. You're going to need to work with the J-PAL webfolks to get the API key

**Comment by larsvilhuber** [comment]
Is this done? @jimhshen

**Comment by jimhshen** [comment]
Done
