### ISSUE TITLE
Proofread author names

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#130]
Somebody needs to proofread all the author names

- source is in "config.yml"
- currently, the LaTeX code with names is entirely written out by Rmd, so the fix should be in the Rmd/ config.yml file.

**Comment by jimhshen** [comment]
From the edits you made it looks like the issue occurs when you try to separate first and last names (e.g, for citations)?

**Comment by larsvilhuber** [comment]
No, "Phillip" was misspelled (I checked against an email from him). The other edits are for separating first and last name, and are not direct related to this issue. all names should be checked for correct spelling (again?)

--
Lars Vilhuber
on mobile device

________________________________

**Comment by larsvilhuber** [comment]
See note in #131 . @jimhshen should close the issue as appropriate.
