### ISSUE TITLE
Edit Chapter foreword on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#134]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Evan


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists
-- | -- | -- | -- | -- | --
Good | None | None | None | ok, might want a final check | none

**Comment by jimhshen** [comment]
Edited printauthor function for web version to print Danny's title.

"Dataset" to "data set"
