### ISSUE TITLE
Edit Chapter intro on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#135]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Jim


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists
-- | -- | -- | -- | -- | --
Good | Updated chetty graph and intro figure 1 to helvetica, higher resolution, resized | Changed caption to "Case studies at a glance", formatted table | None | good | none
