### ISSUE TITLE
Edit Chapter dua on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#138]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Jack


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
-Added lines titles for subchapters 1.8 and 2.3 | None | None | Good | Moved the first breakout box a paragraph earlier to fix spacing -- seems a bit better, but might want to check | None | -Citation for "Future  of  Privacy  Forum,  and  Actionable  Intelligence  for  Social  Policy." needs a last accessed date-Citation for "Data Sharing:  Creating AgreementsIn support ofcommunity-academic partnerships." needs a last accessed date + has missing space in the title-The first citation in the references has a multitude of authors -- probably not a problem, but wanted to flag-Removed a hyperlink from second breakout box that linked to the same resource cited in its associated footnote (and listed in references)-Removed a hyperlink from the "Drafting the Request" section that was broken, but theoretically linked to a portion of the same resource that is already cited in the paragraph-Some index terms are duplicated (i.e., with different capitalizations, pluralizations, etc.) | yes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Website citations in bib do not need accessed dates because they have publication years

Mirrored removal of URLs in latex document.

Fixed bib entry

**Comment by larsvilhuber** [comment]
Confused.


  *    website citations always need access dates.
  *   Publications available only on a website (not a journal, not a DOI) need access dates. Do not remove access dates.
  *   I'm assuming "removal of URL" means "remove URL from text and replace with citation.

The only URLs that do not need access dates are DOIs.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
https://owl.purdue.edu/owl/research_and_citation/chicago_manual_17th_edition/cmos_formatting_and_style_guide/web_sources.html

Chicago style only asks for an access date if no other website date is available.

Yes, removal of URL meant removing it from text and replacement with citation,

**Comment by larsvilhuber** [comment]
This is the first I hear of this, but of course your reference is clear. However:

Unless this has been done elsewhere, please do not remove the access date.

Unless it has a DOI, it has absolutely no permanence. AEA rules require the access date for "unpublished" documents. A clear working paper series can omit the access date, but many of these documents are NOT in any robust (academic) working paper series, and must be assumed to be transitory. I can provide examples of journal articles (without DOI) that have disappeared, and tons of "organizational" PDFs that have disappeared (including official government documents). A PDF on a random website is a "unpublished document".

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
I have not removed any access dates from zotero items, my comment about access dates was in reference to the initial editor (Jack) comment that various citations needed access dates.

If we want to add access dates even though Chicago style doesn't require them, can we go back and add access dates all in one go on zotero after the formatting edits are done? I don't think that's something that authors need to proof?

**Comment by larsvilhuber** [comment]
No, authors do not need to proof that.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
