### ISSUE TITLE
Edit Chapter irb on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#139]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Liz

Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
good (added lines) | None | Replace \hline with \toprule, \midrule, and \bottomruleFYI, the table puts itself at the end of the chapter when I float it so I didn't add [t] to \begin{table} | Good | - one weird spacing before breakout box. moving author about section to a new page seemed to fix it | good (one list uses roman numerals but is a quote from so it makes sense in that context) | - websites in body need last access dates | yes

**Comment by jimhshen** [comment]
Updated URLs with access dates

Reformatted table slightly in latex

Question: should we remove the Cornell law links for the print version where they end up being footnotes in pseudo section headers?

![image](https://user-images.githubusercontent.com/20117905/102273106-d36a5880-3eef-11eb-8805-14d63063c45d.png)

**Comment by larsvilhuber** [comment]
Aren't those supposed to be references?

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Alternatively, simply make them links that are invisible in the print version, and resolve in the PDF.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
