### ISSUE TITLE
Edit Chapter discavoid on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#140]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by larsvilhuber** [comment]
Need to return to Table 1.

**Comment by larsvilhuber** [comment]
Content changes in https://github.com/admindatahandbook/book-latex/commit/4309be92b236d808d76313243b6d67651ae596b7#diff-5169d2f33fce472beaa8080d3c48050a122a2d4e7a06495965246587e7096c88

**Comment by larsvilhuber** [comment]
New table at 224d0b5

**Comment by jimhshen** [comment]
![image](https://user-images.githubusercontent.com/20117905/101407676-36813d00-38a9-11eb-856a-abd777ae8172.png)

How does this look?

**Comment by larsvilhuber** [comment]
Looks good. Maybe use an empty square? the fully blacked out square looks very dominant, when in fact it shouldn't be. Thanks!

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
![image](https://user-images.githubusercontent.com/20117905/101409461-f079a880-38ab-11eb-9efb-a30331af94e2.png)

Updated it, also added a footnote with a legend (is there a better way of doing that?)

**Comment by larsvilhuber** [comment]
Looks fine to me

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Ok, I'll turn that into Latex next.

**Comment by larsvilhuber** [comment]
Start by making it into a picture, of the right size. For. Printing, that's sufficient.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by jimhshen** [comment]
I think it looks better keeping the visual style of all the other printed tables.

![image](https://user-images.githubusercontent.com/20117905/101515663-97ae1c80-394c-11eb-87cd-487a2c452b93.png)

**Comment by larsvilhuber** [comment]
I guess. Trade-off between excessive splitting of words, and turning a head or a page.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Editor: Jim

Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
good | None | converted table, updated caption in HTML | keep as bboxfix | good | removed one tightlist | updated bibliogrpahy for discavoid (standardize names/initials) | yes (double check bib on final pass)

**Comment by jimhshen** [comment]
Old: 
![image](https://user-images.githubusercontent.com/20117905/101533523-f16e1100-3963-11eb-8787-8ebfd790a188.png)

New:
![image](https://user-images.githubusercontent.com/20117905/101533558-fc28a600-3963-11eb-9384-d3ee10d1ceaa.png)
