### ISSUE TITLE
Edit Chapter nbirdt on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#145]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Evan


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content
-- | -- | -- | -- | -- | -- | --
good | good | none | none | good | none | removed extra space in chapter citation, new page for about authors section

**Comment by jimhshen** [comment]
Updated URLs with last accessed dates.

Ready for authors to proof
