### ISSUE TITLE
Edit Chapter ahc on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#147]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Mike


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
-split Laura's title to wrap onto two lines | none | none | none |   | none | newpage for "about the authors" | yes

**Comment by jimhshen** [comment]
Added CFR bibliography entries
Added accessed dates
