### ISSUE TITLE
Edit Chapter sfusd on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#148]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Jack


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
-added line break to " Framework for Converting Operational Data toAnalytical Data for Research" | good -- added a period to the caption | none | none | good | good -- removed tightlist command | -San Francisco Unified School District (2014) doesn't have a last accessed date-San Francisco Unified School District (2019) does not have a url (non-online resource?)-New paged the about the authors page-No acknowledgements; not sure if there were supposed to be any | yes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Flag "SFUSD Chief of Human Resources, Daniel Menezes, has continued a relationship with Professor Susanna Loeb, then at Stanford but now at Brown University."
