### ISSUE TITLE
Edit Chapter dime on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#150]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Evan


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
Good | Good | None | None | Good | Flag-- bulleted list in 1.7.3 goes over a page. Confirm that this is alright? Lists in 1.5.1, 1.7.3 converted from \tightlist to enumerate |

**Comment by jimhshen** [comment]
Updated URLs and citations

Copied over content changes from Anja to Rmd version
