### ISSUE TITLE
Edit Chapter imf on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#151]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Jack


Good | None | None | None | Good= | None | - Citation for "Learning from the Global Leader:  An Analysisof Electric Car Subsidies in Norway" has neither DOI or URL/accessed date + maybe typo in the title?-Some index terms are duplicated (i.e., with different capitalizations, pluralizations, etc.) -Moved hyperlink to footnote in section "Sustainability and Continued Success" | yes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Updated footnote hyperlink for consistent style and access date

Will need to flag bibliography entry for authors in final proof

Capitalized section titles
