### ISSUE TITLE
Edit Chapter indonesia on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#152]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Mike


-split 0.2.1. Using admin... into two lines to avoid the hyphen-split 0.2.2 Using admin... into two lines to avoid the hyphen-split 0.4.2 Admin.... into two lines to avoid the hyphen | look good to me. Might consider shortening the caption for figure 2 (don't think fig 2 is appearing where it should be, but I am not 100% sure how to fix) | None | None | Good. Added a \newpage before 0.4 section to fix weird spacing before 0.4 started. | good -- removed tightlist command | -World bank needs last accessed date | Yes |   |   |   |   | Jones, Maria, Florence Kondylis, John Loeser, and Jeremy Magruder., 2019 | : "rwanda" not capitalized
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Moved figure 2 to the correct spot in text by using h!t instead of t.

World Bank citation does not need accessed date as it is a report with a publication date.

Changed figures back to color version
