### ISSUE TITLE
Updating index terms

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#155]
List of index terms that need to be changed. Add to this list, and check off those that are done. Do not remove terms.

- [ ] institutional review board -> Institutional Review Board as master

**Comment by jimhshen** [comment]
[Chicago Manual of Style](https://www.chicagomanualofstyle.org/16/ch16/ch16_sec011.html) says the index words should be lower case unless proper nouns?

![image](https://user-images.githubusercontent.com/20117905/97514741-dd4af300-1965-11eb-9c49-8ec5ea50a1d9.png)

**Comment by larsvilhuber** [comment]
Good find. OK.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
I'm sure there's going to be entries that need to be updated in the other direction as I go through the chapters...

**Comment by larsvilhuber** [comment]
I'll back it out.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Yeah, but should be in a branch that has ONLY the index mapping file changed. and we pull it in at the end.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
