### ISSUE TITLE
Need to define a style "breakout box" for both LaTeX and online

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#19]
Multiple chapters use "breakout boxes". Need to define a style.

**Comment by jimhshen** [comment]
defined style bbox in css, generated using https://bookdown.org/yihui/bookdown/custom-blocks.html

need to play with style for final look, will depend on what other colors we use in the book

**Comment by larsvilhuber** [comment]
Need to keep this open for the LaTeX part of it.

**Comment by larsvilhuber** [comment]
Addressed in c613fc9
