### ISSUE TITLE
Add supplementary materials

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#192]
Write script for webinar videos

**Comment by larsvilhuber** [comment]
The text should be 

"This chapter was presented by the authors as a webinar on (DATE). A [recording of the webinar](link to youtube within playlist) and [slides](link to slides) are available."

**Comment by larsvilhuber** [comment]
be3ac95d7f446ad1a8e760f11d4df8180cb7f55f fixes this.
