### ISSUE TITLE
References disappeared in testing

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#195]
The end of chapter references have disappeared in the current testing version of the Handbook.

**Comment by larsvilhuber** [comment]
Weird. They were present when I ran the second-to-last run... Reference links point to the end of all the chapters - as if it wants to use a global reference list - did I take out some conditional processing that was needed?

**Comment by jimhshen** [comment]
Running build.R locally doesn't have this issue, but also revealed a separate issue with your table printing functions in the security and IAB chapters breaking the table references.

**Comment by larsvilhuber** [comment]
I have been trying to debug those locally and remotely. Remember: there is​ no remote build, but there is a docker build available. I cannot pin down why the print function is not working. Under what appear to be identical circumstances, it sometimes works, and sometimes doesn't.

I will fix it.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
9bd2ec2 Updating testing with latest build from master that has both the latest fixes, seems to have references, and does not have the table creation problem. No code was changed - not sure where the instability in the build process comes from. 

Build happened on 
```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Leap 15.2
other attached packages:
[1] bookdown_0.20

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    knitr_1.31     xfun_0.20     
```
