### ISSUE TITLE
Adjust ebook 

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#196]
- [x] Adjust font of headings
- [x] Move copyright of chapters 
- [x] Confirm references are in ebook
- [x] Manually add in the missing links
- [x] Fix double slashes in web links
- [x] ensure ebook passes validation at  http://validator.idpf.org/. 
- [x] remove the printed "(PART)"
- [ ] Adjust remaining <br> (in Security chapter/table)

**Comment by larsvilhuber** [comment]
@jimhshen Can you play around with addressing these things, and ensure they work with the web version? I.e., moving copyright to the end of the chapter *only* for the ebook means they do *not* show up in the web version. etc. Use a new "ebook_196" branch for that.

**Comment by larsvilhuber** [comment]
@ewillia3 @jimhshen I think all issues (except the empty references) are addressed. One caveat:

- for the IMF chapter, where the copyright is NOT with the authors, the copyright line still appears. I don't see an easy answer to this, except for one option: to make the copyright notice a footnote (probably numbered). A bit more complicated, but could be done.
-

**Comment by larsvilhuber** [comment]
Here's a link of all the links that need to be adjusted manually:
```
Hyperlink target u'EPUB/text/ch007.xhtml#olda' not found
Hyperlink target u'EPUB/text/ch005.xhtml#cct' not found
Hyperlink target u'EPUB/text/ch010.xhtml#tab%3aoverviewtable' not found
Hyperlink target u'EPUB/text/ch009.xhtml#discavoid' not found
Hyperlink target u'EPUB/text/ch005.xhtml#fig%3aintrochetty' not found
Hyperlink target u'EPUB/text/ch011.xhtml#sec%3adiffpriv-appendixa' not found
Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig2' not found
Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig3' not found
Hyperlink target u'EPUB/text/ch016.xhtml#tab%3apcritable1' not found
Hyperlink target u'EPUB/text/ch016.xhtml#tab%3apcritable2' not found
Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure3' not found
Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure2' not found
Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure1' not found
Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure5' not found
Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure4' not found
Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable2' not found
Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable3' not found
Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable1' not found
Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable4' not found
Hyperlink target u'EPUB/text/ch007.xhtml#pcri' not found
Hyperlink target u'EPUB/text/ch005.xhtml#fig%3aintrofig1' not found
Hyperlink target u'EPUB/text/ch010.xhtml#iab' not found
Hyperlink target u'EPUB/text/ch005.xhtml#dua' not found
Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure3' not found
Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure2' not found
Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure1' not found
Hyperlink target u'EPUB/text/ch005.xhtml#security' not found
Hyperlink target u'EPUB/text/ch007.xhtml#iab' not found
Hyperlink target u'EPUB/text/ch005.xhtml#ahc' not found
Hyperlink target u'EPUB/text/ch014.xhtml#tab%3aoldatable2' not found
Hyperlink target u'EPUB/text/ch014.xhtml#tab%3aoldatable1' not found
Hyperlink target u'EPUB/text/ch010.xhtml#security' not found
Hyperlink target u'EPUB/text/ch011.xhtml#sec%3akey-choices' not found
Hyperlink target u'EPUB/text/ch005.xhtml#discavoid' not found
Hyperlink target u'EPUB/text/ch010.xhtml#diffpriv' not found
Hyperlink target u'EPUB/text/ch008.xhtml#security' not found
Hyperlink target u'EPUB/text/ch005.xhtml#imf' not found
Hyperlink target u'EPUB/text/ch018.xhtml#fig%3asfusdfigure1' not found
Hyperlink target u'EPUB/text/ch005.xhtml#tab%3aintrotable1' not found
Hyperlink target u'EPUB/text/ch010.xhtml#irb' not found
Hyperlink target u'EPUB/text/ch008.xhtml#diffpriv' not found
Hyperlink target u'EPUB/text/ch008.xhtml#discavoid' not found
Hyperlink target u'EPUB/text/ch007.xhtml#discavoid' not found
Hyperlink target u'EPUB/text/ch022.xhtml#fig%3aindonesiafigure1' not found
Hyperlink target u'EPUB/text/ch005.xhtml#sfusd' not found
Hyperlink target u'EPUB/text/ch005.xhtml#dime' not found
Hyperlink target u'EPUB/text/ch019.xhtml#fig%3acctfigure1' not found
Hyperlink target u'EPUB/text/ch005.xhtml#irb' not found
Hyperlink target u'EPUB/text/ch007.xhtml#sfusd' not found
Hyperlink target u'EPUB/text/ch019.xhtml#tab%3accttable1' not found
Hyperlink target u'EPUB/text/ch005.xhtml#diffpriv' not found
Hyperlink target u'EPUB/text/ch007.xhtml#ahc' not found
Hyperlink target u'EPUB/text/ch005.xhtml#indonesia' not found
Hyperlink target u'EPUB/text/ch005.xhtml#olda' not found
Hyperlink target u'EPUB/text/ch008.xhtml#sfusd' not found
Hyperlink target u'EPUB/text/ch005.xhtml#iab' not found
Hyperlink target u'EPUB/text/ch007.xhtml#nbirdt' not found
Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig3' not found
Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig2' not found
Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig1' not found
Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig4' not found
Hyperlink target u'EPUB/text/ch016.xhtml#fig%3apcrifigure1' not found
Hyperlink target u'EPUB/text/ch016.xhtml#fig%3apcrifigure2' not found
Hyperlink target u'EPUB/text/ch005.xhtml#nbirdt' not found
Hyperlink target u'EPUB/text/ch007.xhtml#diffpriv' not found
Hyperlink target u'EPUB/text/ch005.xhtml#pcri' not found
Hyperlink target u'EPUB/text/ch007.xhtml#cct' not found
Hyperlink target u'EPUB/text/ch007.xhtml#tab%3asecuritysummarytable' not found
Hyperlink target u'EPUB/text/ch007.xhtml#dua' not found
Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig5' not found
Hyperlink target u'EPUB/text/ch011.xhtml#diffpriv-appendixa' not found
Hyperlink target u'EPUB/text/ch007.xhtml#dime' not found
Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig1' not found
Hyperlink target u'EPUB/text/ch010.xhtml#dua' not found
Hyperlink target u'EPUB/text/ch011.xhtml#discavoid' not found
Hyperlink target u'EPUB/text/ch013.xhtml#tab%3aiabtable1' not found
Hyperlink target u'EPUB/text/ch013.xhtml#tab%3aiabtable2' not found
```
In part because the conversion from Markdown to XHTML strips out the <span> elements that contain the id tags in the web version (for some of them) and as we already know, does not adjust links that link to other files within the overall document (as it does in the web version)

**Comment by larsvilhuber** [comment]
Implementing the links:

Between the validator and the list below (from conversion to mobi), fix as follows:

- for "hanging links" (`Fragment identifier is not defined.`), find the file that goes with the link, and add to the link (e.g., `a href="#cct"` becomes `a href="ch019.xhtml#cct"`)
- for missing targets for figures (e.g. `ch011.xhtml#fig%3adpfig5' not found`), create the target by finding the figure (may need to reference the Rmd file), finding the class tag and adding the target id: `ch011.xhml:814: <div class="figure">` becomes `ch011.xhml:814: <div id="fig:dpfig5" class="figure">`
- for missing targets for tables (e.g., `ch010.xhtml#tab%3aoverviewtable' not found`), create the target by finding the table, finding the table tag, and adding the target id: `ch010.xhtml:118: <table class="table"` becomes `ch010.xhtml:118: <table id="tab:overviewtable" class="table"`

These three steps should fix all of the issues below and in the validator. This should be done in the "issue-196-ebook" branch

> ```
> Hyperlink target u'EPUB/text/ch007.xhtml#olda' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#cct' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#tab%3aoverviewtable' not found
> Hyperlink target u'EPUB/text/ch009.xhtml#discavoid' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#fig%3aintrochetty' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#sec%3adiffpriv-appendixa' not found
> Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig2' not found
> Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig3' not found
> Hyperlink target u'EPUB/text/ch016.xhtml#tab%3apcritable1' not found
> Hyperlink target u'EPUB/text/ch016.xhtml#tab%3apcritable2' not found
> Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure3' not found
> Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure2' not found
> Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure1' not found
> Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure5' not found
> Hyperlink target u'EPUB/text/ch020.xhtml#fig%3adimefigure4' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable2' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable3' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable1' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#tab%3adiffprivtable4' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#pcri' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#fig%3aintrofig1' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#iab' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#dua' not found
> Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure3' not found
> Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure2' not found
> Hyperlink target u'EPUB/text/ch015.xhtml#fig%3anbirdtfigure1' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#security' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#iab' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#ahc' not found
> Hyperlink target u'EPUB/text/ch014.xhtml#tab%3aoldatable2' not found
> Hyperlink target u'EPUB/text/ch014.xhtml#tab%3aoldatable1' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#security' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#sec%3akey-choices' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#discavoid' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#diffpriv' not found
> Hyperlink target u'EPUB/text/ch008.xhtml#security' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#imf' not found
> Hyperlink target u'EPUB/text/ch018.xhtml#fig%3asfusdfigure1' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#tab%3aintrotable1' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#irb' not found
> Hyperlink target u'EPUB/text/ch008.xhtml#diffpriv' not found
> Hyperlink target u'EPUB/text/ch008.xhtml#discavoid' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#discavoid' not found
> Hyperlink target u'EPUB/text/ch022.xhtml#fig%3aindonesiafigure1' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#sfusd' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#dime' not found
> Hyperlink target u'EPUB/text/ch019.xhtml#fig%3acctfigure1' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#irb' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#sfusd' not found
> Hyperlink target u'EPUB/text/ch019.xhtml#tab%3accttable1' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#diffpriv' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#ahc' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#indonesia' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#olda' not found
> Hyperlink target u'EPUB/text/ch008.xhtml#sfusd' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#iab' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#nbirdt' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig3' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig2' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig1' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig4' not found
> Hyperlink target u'EPUB/text/ch016.xhtml#fig%3apcrifigure1' not found
> Hyperlink target u'EPUB/text/ch016.xhtml#fig%3apcrifigure2' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#nbirdt' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#diffpriv' not found
> Hyperlink target u'EPUB/text/ch005.xhtml#pcri' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#cct' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#tab%3asecuritysummarytable' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#dua' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#fig%3adpfig5' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#diffpriv-appendixa' not found
> Hyperlink target u'EPUB/text/ch007.xhtml#dime' not found
> Hyperlink target u'EPUB/text/ch013.xhtml#fig%3aiabfig1' not found
> Hyperlink target u'EPUB/text/ch010.xhtml#dua' not found
> Hyperlink target u'EPUB/text/ch011.xhtml#discavoid' not found
> Hyperlink target u'EPUB/text/ch013.xhtml#tab%3aiabtable1' not found
> Hyperlink target u'EPUB/text/ch013.xhtml#tab%3aiabtable2' not found
> ```

**Comment by jimhshen** [comment]
The security chapter example tables become unreadable with the colored backgrounds. I think its probably easiest to just remove the colors?

![image](https://user-images.githubusercontent.com/20117905/108088031-017e2d00-7046-11eb-824a-727be2ca5532.png)

Is there a way to scale the badges down? They might do strange things to the formatting depending on the configuration of the page and the reader.

![image](https://user-images.githubusercontent.com/20117905/108096494-072c4080-704f-11eb-80bf-17a2f992a08a.png)

Do we want to include the online-only appendices in the ebook? They are currently in it and I don't see a problem with that but wanted to make sure.

**Comment by jimhshen** [comment]
Fixed the links - not sure if the table and figure references will also need the ch0[number].xhtml in front of the id tags? Let me know if those still don't work when you rebuild the ebook.

**Comment by larsvilhuber** [comment]
Yes, all href need a qualified path. It is a spec error NOT to have the filename in there, even if it is internal. That's why I mentioned that some cases will be subject to TWO corrections.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Got it, added those in as well

**Comment by larsvilhuber** [comment]
Nope. You added the wrong targets. Targets don't get "#". I'll fix.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
DO NOT DELETE THIS BRANCH.
