### ISSUE TITLE
Latex output issue with makecell for IAB table

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#26]
I tried building it as a PDF by adding "always_allow_html: true" in the index.Rmd header and removing the rmdwarning code block (this also breaks the latex output, "Environment rmdwarning undefined", haven't figured out how to [define latex environments](https://bookdown.org/yihui/bookdown/custom-blocks.html) yet but figure that should be an easy fix).

The only issue with building the document otherwise is when trying to implement [this method](https://stackoverflow.com/questions/52944533/wrap-text-in-knitrkable-table-cell-using-n) of getting [IAB table 1](https://jimhshen.github.io/admindatahandbook/institute-for-employment-research-germany-access-to-administrative-labor-market-data-for-international-researchers.html#tab:iabtable1) to render in PDF (The function is in [_plot_iab.R](https://github.com/jimhshen/admindatahandbook/blob/master/programs/_plot_iab.R)). It gives an undefined control sequence error for the table where it uses makecell. The specific error in the R console is here:

Undefined control sequence.
l.857 ...{1em}Population / Sample Size & \makecell
                                                  [l]{2% random sample (more...

I tried building the same table as in the stackexchange example and it gives (presumably) the same error, as follows:

Undefined control sequence.
l.853 a & \makecell
                   [l]{one\\\two}\\\

Not having any experience with latex, unsure if its because we need to install the makecell package somewhere,  an issue with the way that bookdown converts the newline "\n" into "\\" when it goes from markdown to tex, or something else?

Wanted to flag this early because if there's some reason that this can't work, will need to rewrite the table. The other table with line breaks, [olda table 1](https://jimhshen.github.io/admindatahandbook/ohio-and-the-longitudinal-data-archive-developing-mutually-beneficial-partnerships-between-state-government-and-the-research-community.html#tab:oldatable1) is built using pander which doesn't use the makecell function when converted to tex.

**Comment by larsvilhuber** [comment]
I will handle the latex environment thing.

The "%" sign is breaking your table. "%" is a comment symbol in Latex, making the rest of the line "invisible". Use "\%", and see what the internets have to say about Rmarkdown with % symbols in Latex.
--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Sorry, looks like you don't get email updates when I edit the initial issue - I had tried running the code from [this example](https://stackoverflow.com/questions/52944533/wrap-text-in-knitrkable-table-cell-using-n) instead of the table that I generated, and it was giving the following error when rendering with bookdown:

Undefined control sequence.
l.853 a & \makecell
[l]{one\\two}\\

The table works fine when knitting from from an Rmd directly, without using bookdown.

I have updated the IAB table function to work when run outside of bookdown for both HTML and PDF (see [testpage.pdf](https://github.com/jimhshen/admindatahandbook/blob/master/test-page.pdf) for the output), but the issue remains when trying to build the PDF using bookdown.

**Comment by larsvilhuber** [comment]
Is this solved via #26 @jimhshen ?

**Comment by jimhshen** [comment]
No, given the last time we talked about this you said to leave the latex to you

**Comment by larsvilhuber** [comment]
Ah, I misread. Wanted to ensure that the HTML output was clean, but the subject line clearly says "LaTeX". My bad.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
