### ISSUE TITLE
footnote citations not showing up in references at end of chapter

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#29]
See the [Aurora chapter](https://jimhshen.github.io/admindatahandbook/aurora-health-care-using-electronic-medical-records-for-a-randomized-evaluation-of-clinical-decision-support.html) for an example. The first footnote cites Hentel 2019 and CMS 2018, which are both in the bibliography file and the citation renders properly, but does not show up in the references section for the Aurora chapter. Both citations do show up in the references at the end of the book (currently shows up immediately after the "Trademarks" section without its own header, which will need to change), but the links to those citations are broken.

I did some digging and am not sure that there's a bookdown solution to this issue. No issues related to this seem to exist on the bookdown repository, and didn't manage to find any examples of anyone getting this to work. The closest I found was [this](https://github.com/OnTheLine/otl-bookdown), which doesn't have a references section in each chapter, only has references at the end of the book, and doesn't use links to the reference within the citation (its clunky but at least its not obviously broken?).

How do you want to handle this?

**Comment by jimhshen** [comment]
Note that the solution listed in the pandoc manual of using a yaml header with nocite: @references doesn't do anything within each chapter.

**Comment by larsvilhuber** [comment]
This seems to work now with the workaround.
