### ISSUE TITLE
physical security summary plot

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#41]
I generated the [current version of the plot](https://jimhshen.github.io/admindatahandbook/assets/security/summarytable.png) using ggpubr, but adding ggpubr to the libraries every time we push the handbook increased the build time from ~5 minutes to ~15, so I saved the output as an image and had it load that way. The code from _plot_physical (currently commented out) is below.

```
# Summary Table Function
plotallmechs<-function(){
summarymechs <- read.csv("./assets/security/mechanisms.csv")

# Create a ggtextable
allmechs <- ggtexttable(summarymechs, rows = NULL, theme = ttheme("classic"),
                        cols=c("Name",
                               "Researcher\nAgency\nOver\nAnalysis\nComputer",
                               "  Location  \nof Data and\nAnalysis\nComputer",
                               "  Location  \nof Access\nComputer",
                               "   Access   \nSecurity",
                               " Range of \nAnalysis\nMethods\nAvailable"))

# Specify colors for significant p-values

# Coloring the table conditionnally using `ggpubr::table_cell_bg()`

list = c("agency", "location","access","sec","range")

for (i in list) {
  summarymechs <- summarymechs %>%
    mutate(
      fill = ifelse(summarymechs[, i] == 1, config$colors$aspect_low, ifelse(summarymechs[, i] == 2, config$colors$aspect_med, config$colors$aspect_high)),
      color="black"
    )
  for(j in 1:nrow(summarymechs)){
    row = j+1
    column = which(colnames(summarymechs) == i)
    allmechs <- table_cell_bg(
      allmechs, row = row, column = column,
      fill = summarymechs$fill[j], color = summarymechs$color[j]
    )
  }
}

print(allmechs)
}
```

[There should be a way to do it with kableExtra](https://stackoverflow.com/questions/51509450/r-conditional-highlighting-kable) (which we already load for other tables) but I haven't had a chance to get to get it to work yet. Was trying to figure out how to get the mutate argument to work properly, but figure you could do this a lot faster if you wanted to update the chart.

**Comment by larsvilhuber** [comment]
put the chart in Excel, then read the Excel with R and simply print it with kable() %>% kabel_styling()...

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Do you want me to generate a colored chart in excel and read it into R, or put the data in xlsx and read it in? The data is already being imported from a CSV, what does converting to XLSX do on top of that?

My question is around the kable styling, specifically the mutate command to get the column background colors to work.

**Comment by larsvilhuber** [comment]
OK, then forget about Excel. For now, put it in without colors (note: colors are not 508-compliant if they convey information, so we may have to think of something else anyway). I'll take a stab at it after Sept 28.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
