### ISSUE TITLE
Integrate foreword

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#44]

**Comment by jimhshen** [comment]
@larsvilhuber For Danny's indented paragraphs, I used the solution [outlined here](https://stackoverflow.com/questions/47087557/indent-without-adding-a-bullet-point-or-number-in-rmarkdown). 

I added the following to style.css and surrounded the indented paragraphs with a "nobullet" block.
````
.nobullet li {
  list-style-type: none;
}
```

I'm guessing this will have some effect on the PDF version (the same way that our breakout boxes do) - will this work to generate an indented block in the PDF as well, or is there a separate solution that should be used there instead?

**Comment by jimhshen** [comment]
Hm, for some reason that worked locally but doesn't work on the testing site. Will investigate further.

**Comment by jimhshen** [comment]
The problem was the testing folder not updating again.

**Comment by larsvilhuber** [comment]
I will need to come up with a separate solution. I'll tackle that when I next do PDF stuff.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
The HTML version is fixed now, can see it [here](https://admindatahandbook.mit.edu/book/v1.0-rc5/foreword.html).
