### ISSUE TITLE
Integrate overview SDL chapter

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#45]

**Comment by jimhshen** [comment]
I've pulled the latest version locally to update the brackets, and when I build the book the overviewtable in the SDL chapter isn't building.

**Comment by larsvilhuber** [comment]
It is building for me - are you sure you let it install the additional package that is necessary? (readODS)

For me, the ref is not working.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Your table needed a caption. Also updated the chapter with the proper index tags. There's some weird line spacing in the markdown file that suggested it might have been an attempt at getting line breaks with no spacing in between, not sure if it was intended or not so I didn't touch it. Example below.

```
Rather, this chapter provides an overview of the concepts and more widely-used methods of SDL.
Relative to other primers that cover similar material, we focus more closely on the advantages and disadvantages of various methods from the perspective of data users.
This chapter can serve as a reference that data providers and data users can use to discuss which forms of SDL are appropriate and will satisfy the needs of both parties. In particular, we focus on how common SDL tools affect different types of statistical analysis as well as the kind of confidentiality protections they support, drawing heavily on @abowd_economic_2015. SDL is a broad topic with a vast literature, starting with @fellegi_question_1972. Naturally, this brief summary is not a replacement for the textbook treatment of SDL in @duncan_statistical_2011.
Finally, SDL methods must be implemented and deployed, and we provide pointers to existing "off-the-rack" tools in a variety of platforms (Stata, R, and Python). Readers might also consult other summaries and guides, such as @dupriez_dissemination_2010, @world_bank_dime_nodate, @kopper_j-pal_2020, and @liu_statistical_2020.
```

**Comment by larsvilhuber** [comment]
Those line breaks can be removed, I didn't know that Markdown is sensitive to that (LaTeX is not).

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Markdown isn't, but having a double space at the end of it would have resulted a new line without a separation. Was unsure if that was the intention or not.
