### ISSUE TITLE
Update publishing method

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#48]
Not sure what my unintentionally brilliant idea was, but here's the issue assigned to you to fiddle with the scripts.

**Comment by larsvilhuber** [comment]
This now works, see README for instructions.

**Comment by jimhshen** [comment]
When we push this to the main site, is it going to end up being admindatahandbook.mit.edu/book/index.html, or admindatahandbook.mit.edu/book/version/index.html? Because if its the latter we need to ask Evan to update all the links she's set up anticipating that it would be the first one.

**Comment by larsvilhuber** [comment]
Have her update all the links to have "book/latest/". I'll fix that.

are her links pointing to the short names?

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Yes, the links are pointing to the short names.

**Comment by larsvilhuber** [comment]
OK, my test fix works. I'll deploy it on the main repo


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
https://github.com/admindatahandbook/book/runs/1165993012

```
Deploy action fails
Run peaceiris/actions-gh-pages@v3.7.0-8
Dump inputs
Setup auth token
Prepare publishing assets
Setup Git config
Create a commit
Push the commit or tag
  /usr/bin/git push origin published_version
  remote: error: GH006: Protected branch update failed for refs/heads/published_version.        
  remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
  To https://github.com/admindatahandbook/book.git
   ! [remote rejected] published_version -> published_version (protected branch hook declined)
  error: failed to push some refs to 'https://github.com/admindatahandbook/book.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

**Comment by larsvilhuber** [comment]
Yes, I know. We are stepping on each other's toes. I will stop working in your fork.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
