### ISSUE TITLE
Some assets seem not to be changed in deploy

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#52]
Might need to remove `keep_files=true` from main.yml

**Comment by jimhshen** [comment]
It seems like when deploying to the testing folder, anything that goes into a folder gets sent into a subfolder with the same name if the folder already exists.

When I was trying to update the CSS file for the foreword, I noticed that the style.css file within assets/css was not updated, but also within assets there was a assets/assets/css folder.
