### ISSUE TITLE
Customize CSS

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#53]
Anja raised this point earlier when discussing Latex, we should see if we can customize the CSS for the web output so we use the same fonts online as in the book. Right now I switched the default output to serif instead of sans, but if we can switch the headers to use helvetica (same as the handbook cover), and the body to whatever that ends up being, that would be good.

**Comment by larsvilhuber** [comment]
style.css is your friend, but in general, AFAIK, the optimal font for printing is not the same as the optimal font for reading online. Ask the web/style folks for suggestiongs

Changing the default does not change the font, only style.

**Comment by larsvilhuber** [comment]
@jimhshen one last stab at this? Can you ask the web folks for guidance?
