### ISSUE TITLE
Add supplemental materials as a section

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#56]
- links to author websites and portals
- links to webinar recording
- links to slides (need DOI for slides)

**Comment by jimhshen** [comment]
Do we want to link to the authors websites directly from their about the authors section? The IMF chapter authors did that on their own.

How do we want to host the slides? In the landing page repository somewhere?

**Comment by larsvilhuber** [comment]
*    authors' websites: I encourage that (including for the editor's bios...). You will need to get in contact with each of them to get that info.
  *   slides: same place as we will store the PDF version of the handbook... which we haven't figured out yet. How does J-PAL preservation policy work? If not, I strongly suggest https://dspace.mit.edu/ (create a "collection" there under the J-PAL community<https://dspace.mit.edu/handle/1721.1/39118> that is specific to the handbook. Ask who administeres that. See an example using a different Dspace instance here<https://ecommons.cornell.edu/handle/1813/30502>.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
This section would NOT be in the LaTeX / print version. The Print version would just point to the DOI of the chapter for additional information (in title footnote).

**Comment by larsvilhuber** [comment]
![image](https://user-images.githubusercontent.com/7022712/94758741-f31bc700-036b-11eb-9c1b-b4f386f61c98.png)

**Comment by larsvilhuber** [comment]
![image](https://user-images.githubusercontent.com/7022712/94758760-062e9700-036c-11eb-99b7-0ea497b32e57.png)
