### ISSUE TITLE
Incorporate DP chapter

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#64]

**Comment by jimhshen** [comment]
Pushed an update.

Two of the tables still need work, and there's a bunch of chapter cross references that didn't convert properly between latex and markdown, but I think that fixing the cross references can wait until after we do the editorial stuff.

**Comment by jimhshen** [comment]
Edited the last two tables for HTML. Had to use a kludgey solution to get table 3's font size smaller. KableExtra doesn't do lists in tables but has the font_size command, pander can do lists in tables but has no way of controlling font size, my solution was to define a custom div in style.css that just has a font size argument and print the div if output is HTML. When rendering locally, this seems to work.

Given the original document from the authors is in Latex, can we just set the latex output for all of the table functions to their original latex code?

**Comment by jimhshen** [comment]
As before, see the private dp chapter repository.

**Comment by larsvilhuber** [comment]
Yes to using their original LaTeX, subject to minor style changes.

There's a kable extra function to auto resize. See https://github.com/larsvilhuber/MobZ/blob/dfc459906d7d1c535ad22907158bd1a1781b828a/README.Rmd#L490
[https://avatars0.githubusercontent.com/u/7022712?s=400&v=4]<https://github.com/larsvilhuber/MobZ/blob/dfc459906d7d1c535ad22907158bd1a1781b828a/README.Rmd#L490>
larsvilhuber/MobZ<https://github.com/larsvilhuber/MobZ/blob/dfc459906d7d1c535ad22907158bd1a1781b828a/README.Rmd#L490>
Contribute to larsvilhuber/MobZ development by creating an account on GitHub.
github.com


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Sorry I wasn't clearer - I couldn't use kable for table 3 because kable doesn't handle lists in tables, and that table is a bunch of lists in the table. I ended up using pander for the table, which necessitated surrounding it with the div tags to modify the font size; otherwise it would be too large and go off the screen.

**Comment by larsvilhuber** [comment]
Completed in e09025aa739534dace107d9ec067f9514af1b015  and 14019d0ff56df75f7fcf9197679c214f2bcaa4bf
