### ISSUE TITLE
Author websites

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#65]
Will edit top comment to be up to date.

**About the editors**
Anja: https://www.worldbank.org/en/about/people/a/anja-sautmann (confirmed)
Iqbal: https://www.povertyactionlab.org/person/dhaliwal (unconfirmed, no likely alternate)
Lars: lars.vilhuber.com (confirmed)
Shawn: https://www.hbs.edu/faculty/Pages/profile.aspx?facId=340064 (unconfirmed)

**Intro**
N/A

**Security**
Jim: https://www.povertyactionlab.org/person/shen
Lars: see above

**DUA**
Amy:  https://gufaculty360.georgetown.edu/s/contact/0033600001nHXCZAA4/amy-ohara (confirmed)

**IRB**
Kathleen: no website (confirmed)

**DiscAvoid**
Ian: ianschmutte.org (confirmed)
Lars:  see above

**DiffPriv**
Alexandra: https://cyber.harvard.edu/people/awood (unconfirmed)
Kobbi: http://people.cs.georgetown.edu/~kobbi/ (unconfirmed)
Micah: https://micahaltman.com/ (unconfirmed)
Salil: https://salil.seas.harvard.edu/ (unconfirmed)

**IAB**
Dana: https://www.iab.de/en/ueberblick/mitarbeiter.aspx/Mitarbeiter/251 (confirmed)
Philipp: https://www.iab.de/754/section.aspx/Mitarbeiter/72110 (confirmed)

**OLDA**
Josh: http://glenn.osu.edu/faculty/glenn-faculty/hawley/ (unconfirmed)

**NBIRDT**
Donna: https://www.unb.ca/faculty-staff/directory/nbirdt/curtis-maillet-donna.html (confirmed)
Ted: https://www.unb.ca/faculty-staff/directory/arts-fr-economics/mcdonald-ted.html (confirmed)

**PCRI**
Josh: https://www.hbs.edu/faculty/Pages/profile.aspx?facId=9961 (confirmed)
Leslie: unknown (unconfirmed)
Therese: no website (confirmed)

**AHC**
Amy: https://economics.mit.edu/faculty/afink (unconfirmed)
Laura: https://www.povertyactionlab.org/person/feeney (confirmed)

**SFUSD**
Eric: https://ed.stanford.edu/faculty/ebetting (unconfirmed)
Moonhawk: https://gse.berkeley.edu/moonhawk-kim (unconfirmed)
Michelle: https://www.colorado.edu/crowninstitute/michelle-reininger-phd (unconfirmed)
Laura: http://www.caedpartners.org/display/CAED/Our+Team (confirmed)
Norma: https://orcid.org/0000-0002-7991-5929 (confirmed)
Jim: see above

**CCT**
Kelsey: http://kelseyjack.bren.ucsb.edu/ (confirmed)
Hugh: unknown (unconfirmed)
Derek: https://drkrynstrng.gitlab.io/ (confirmed)
Brendan: https://sites.google.com/site/bmaughanbrown/ (confirmed)

**DIME**
Arianna: https://www.worldbank.org/en/about/people/a/arianna-legovini (confirmed)
Maria: https://www.worldbank.org/en/about/people/m/maria-ruth-jones (confirmed)

**IMF**
Authors provided links

**Indonesia**
Rema: https://www.hks.harvard.edu/faculty/rema-hanna (confirmed)
Ben: https://economics.mit.edu/faculty/bolken (confirmed)
Abhijit: https://economics.mit.edu/faculty/banerjee (confirmed)
Poppy: https://www.povertyactionlab.org/person/widyasari (confirmed)
Farah: https://www.povertyactionlab.org/person/amalia (confirmed)
Sudarno: https://www.smeru.or.id/en/content/sudarno-sumarto (confirmed)
Vivi: none (confirmed)

**Comment by larsvilhuber** [comment]
Is this integrated? @jimhshen

**Comment by jimhshen** [comment]
All the ones that exist are integrated

**Comment by larsvilhuber** [comment]
lars.vilhuber.com

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
@jimhshen Can we close this?

**Comment by jimhshen** [comment]
Will still need to get it from the DP authors but other than that yes.
