### ISSUE TITLE
Clean up bib files

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#71]
There are 65 warnings about incomplete entries when using bib files in LaTeX

**Comment by jimhshen** [comment]
[Dalenius 1977](https://jimhshen.github.io/admindatahandbook/testing/discavoid.html#ref-dalenius_towards_1977) seems to have the wrong DOI. It goes [here](https://dl.acm.org/doi/10.1145/320613.320616) which doesn't seem like the right article. I found a poorly scanned version [here](https://archives.vrdc.cornell.edu/info7470/2011/Readings/dalenius-1977.pdf) but can't seem to find a DOI for it.

**Comment by larsvilhuber** [comment]
Not every paper has a DOI, though I do not know where the wrong DOI for Dalenious comes from. This is really old, in an obscure journal, but a critical paper for the literature.

Remove the DOI, but do not add the URL you found - that's not something we want to provide in print. (Though I will remove the print URL, but not DOI, in the bibliography anyway).



--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Is the current zotero library up to date? Wanted to make sure I'm not going to break anything that you did a couple of days ago when you last said to not touch Zotero for a bit.

**Comment by larsvilhuber** [comment]
Not using it, all changes are uploaded, go ahead and use it.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
@jimhshen Biblio missing entries now, in various chapters.
```
pandoc-citeproc: reference maats2011 not found
pandoc-citeproc: reference korteweg2019 not found
pandoc-citeproc: reference maats2011 not found
pandoc-citeproc: reference centersformedicaremedicaidservices2018 not found
pandoc-citeproc: reference centersformedicaremedicaidservices2018 not found
pandoc-citeproc: reference aiken2020 not found
pandoc-citeproc: reference bedoyaforthcoming not found
pandoc-citeproc: reference wachter2010 not found
pandoc-citeproc: reference milusheva2020 not found
pandoc-citeproc: reference jones2018 not found
pandoc-citeproc: reference jones2019 not found
pandoc-citeproc: reference ash2018 not found
pandoc-citeproc: reference kondylis2019 not found
pandoc-citeproc: reference galiani2017 not found
```

**Comment by jimhshen** [comment]
The current version of master has an up to date bibliography. I saw those errors earlier today, had to export from Zotero again, which fixed it.

**Comment by larsvilhuber** [comment]
Confirmed.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
