### ISSUE TITLE
Add to processing information how to extract bibliography

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#79]
Should be in `_process` somewhere.

- URL for the Zotero bib
- Setting for desktop Zotero + Better Bibtex
- Requirement to exporting manually via desktop (or using the sync functionality in Better Bibtex)
- name of exported file

**Comment by larsvilhuber** [comment]
@jimhshen This only requires documenting in the "_process/" subdirectory anything needed to handle the Zotero + Better Bibtex config, and then link to the main Markdown directory.

**Comment by jimhshen** [comment]
Done.
