### ISSUE TITLE
Make colors greyscale safe

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#80]
This affects various graphics:
- security chapter
- check author-provided images for grey scale safety

This should not affect the only version, and ideally not the visible color in the PDF.

List of tables and figures: https://docs.google.com/spreadsheets/d/1HTvf7maU_UYvpFY8pDMugXdwmPD0oj9zFiOKpZ8CaTA/edit#gid=570038034 

Raw colors should be grey-scale safe, including having unambiguous patterns, but be printed in PDF in color. Conversion to B&W is done through post-processing of PDF.

**Comment by larsvilhuber** [comment]
Possible colors:
https://colorbrewer2.org/#type=sequential&scheme=GnBu&n=3

**Comment by jimhshen** [comment]
IAB chapter has one plot with 4 qualitative categories, which doesn't have a colorbrewer scheme that satisfies colorblind/print/photocopy safe. However, it does have one that is [colorblind and print safe](https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=4) (note that the IAB plots are already set up to use this scheme, using the RColorBrewer package), and for greyscale safe I think we can use [this](https://coolbutuseless.github.io/2020/04/01/introducing-ggpattern-pattern-fills-for-ggplot/) to alternate the fills?

**Comment by larsvilhuber** [comment]
Good idea! I did something similar in my revision of the intro/Chetty graph, using color and dot/dashed lines to achieve the 4-way printable result in B&W.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
I can install it locally but it has a dialogue screen that pops up. When [trying it on github](https://github.com/admindatahandbook/book/runs/1235931008?check_suite_focus=true) it fails with the following:

```
Error: Failed to install 'ggpattern' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpLbsO45/file4e5cf1a192/ggpattern_0.1.3.tar.gz' had non-zero exit status
```

I can play with the graphs locally for now and if we can't get it to load the package on github I can always save the plot output and upload it as an image

**Comment by larsvilhuber** [comment]
try remotes::install_github("coolbutuseless/ggpattern",upgrade="never")


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
That won't work, because the ggpattern uses a ton of dependencies that probably aren't available in your Docker image.

I've built a custom docker image, to speed up our testing, and to solve this problem.

USAGE (try out in testing)

replace the current docker image with larsvilhuber/ideahandbook:latest

modify the bootstrap and libraries.R scripts to remove the reference to repos=:

14c14
< install.packages(x)
---
> install.packages(x,repos = 'https://cloud.r-project.org/')

add to both (for safety - this is not going to be relevant)

options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/318"))

In principle, all libraries listed in book:master + ggpattern are installed, as are all dependencies for ggpattern.

Give this a try.

We can chat on Monday about this.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by Sautmann** [comment]
Would it not be possible to just ask the authors to do this…?
That would be my go-to choice for this type of issue.
