### ISSUE TITLE
Remove portions of the Evolution part

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#86]
The style guide and such should simply refer to the web page.

**Comment by jimhshen** [comment]
I think the entire section can be moved to a section of the admindatahandbook.mit.edu website? I don't think it particularly fits in with the Handbook itself, and definitely not in the printed version.

**Comment by jimhshen** [comment]
Also will save us pages for printing.

**Comment by larsvilhuber** [comment]
It is part of the online handbook. But is not useful for the printed version.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
Closed with #126
