### ISSUE TITLE
Edits to security chapter

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#91]
- [x] some text has gone missing: 
![image](https://user-images.githubusercontent.com/7022712/95806131-fb152880-0cd4-11eb-8732-f3c2b347bd55.png)

- [x] "badges" on left or right? 
![image](https://user-images.githubusercontent.com/7022712/95806410-98705c80-0cd5-11eb-99a0-6d72b1391eb5.png)

- [x] "badges" need to be increased in size. Normal scaling has the text below 10pt. DPI up? 500px might be the right size.

- [x] right column text needs to bigger (too small to read)
![image](https://user-images.githubusercontent.com/7022712/95806499-ce154580-0cd5-11eb-9ebd-029fe74c8305.png)

**Comment by jimhshen** [comment]
I would say badges on the left, as the right edge of the badge will line up nicely with the left-aligned text, versus the varying lengths of text aligning with the left side of the badge.

For the text size and scaling, is this on latex, HTML, or both?

**Comment by larsvilhuber** [comment]
HTML.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
Check if the images/tables are large enough for you now (I obviously could read the old versions).
