### ISSUE TITLE
Section headers seem to break end of preceding chapters 

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#96]
The format of the end of the introduction (above "01_zz_part_specialtopics.Rmd") is formatted different. This didn't happen for the HTML version when the section break was included in "02_security.Rmd".

![image](https://user-images.githubusercontent.com/20117905/95916875-526bd500-0d77-11eb-8c78-83964cb24f73.png)

This also happens at the end of the Indonesia chapter (above "90_zz_part_appendix.Rmd"). The DP placeholder doesn't have any references or footnotes so it doesn't happen there.

Is there a reason for Latex that this needed to be changed to its own Rmd file?

**Comment by jimhshen** [comment]
Moving the TOC section breaks back into the immediately following file (.e.g "special topics" into "02_security") fixes it for HTML, and is also how [moderndive implements it](https://github.com/moderndive/ModernDive_book/blob/master/02-visualization.Rmd). I kept the latex mainmatter and set counter bits in the same spot as well.

**Comment by larsvilhuber** [comment]
Not sure why. The only difference is that it inserts
```
<!--chapter:end:01_zz_part_specialtopics.Rmd-->
```
at the end of each file, and in this case, that's an empty chapter. Move it back to the previous one. This was a change purely to make it easier to manage, had no functional purpose.

**Comment by jimhshen** [comment]
Fixed
